//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Desktop_Application.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class coin
    {
        public System.Guid coin_uuid__uniqueidentifier { get; set; }
        public string coin_code__nvarchar { get; set; }
        public string coin_name__nvarchar { get; set; }
    }
}
