//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Desktop_Application.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public resource()
        {
            this.users = new HashSet<user>();
            this.principalcompanies = new HashSet<principalcompany>();
        }
    
        public System.Guid reso_uuid__uniqueidentifier { get; set; }
        public string reso_name__nvarchar { get; set; }
        public byte reso_extension__tinyint { get; set; }
        public string reso_description__nvarchar { get; set; }
        public byte[] reso_value__varbinary { get; set; }
        public string reso_externalurlorname__nvarchar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<principalcompany> principalcompanies { get; set; }
    }
}
