//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Desktop_Application.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.preferences = new HashSet<preference>();
            this.sessions = new HashSet<session>();
            this.user1 = new HashSet<user>();
        }
    
        public System.Guid user_uuid__uniqueidentifier { get; set; }
        public string user_username__nvarchar { get; set; }
        public string user_email__nvarchar { get; set; }
        public string user_cellphone__nvarchar { get; set; }
        public string user_password__nvarchar { get; set; }
        public string user_firstname__nvarchar { get; set; }
        public string user_lastname__nvarchar { get; set; }
        public byte user_rol__tinyint { get; set; }
        public string user_extradata__nvarchar { get; set; }
        public Nullable<System.Guid> reso_uuid_picture__uniqueidentifier { get; set; }
        public Nullable<System.Guid> date_uuid_birthdate__uniqueidentifier { get; set; }
        public Nullable<System.Guid> city_uuid__uniqueidentifier { get; set; }
        public Nullable<System.Guid> sess_uuid_used__uniqueidentifier { get; set; }
        public System.Guid sess_uuid_created__uniqueidentifier { get; set; }
        public Nullable<System.Guid> user_uuid_root__uniqueidentifier { get; set; }
        public Nullable<System.Guid> sess_uuid_deleted__uniqueidentifier { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<preference> preferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<session> sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual session session { get; set; }
        public virtual session session1 { get; set; }
        public virtual session session2 { get; set; }
        public virtual resource resource { get; set; }
        public virtual date date { get; set; }
    }
}
