//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace General_Desktop_Application.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class version
    {
        public System.Guid vers_uuid__uniqueidentifier { get; set; }
        public string vers_name__nvarchar { get; set; }
        public System.Guid date_uuid__uniqueidentifier { get; set; }
    
        public virtual date date { get; set; }
    }
}
