USE master;

CREATE DATABASE straad_instituteofcourses_v01;

GO

USE straad_instituteofcourses_v01;

GO

CREATE SCHEMA build_general;

GO

CREATE TABLE build_general.[state] (stat_uuid uniqueidentifier NOT NULL, stat_value nvarchar(max) NOT NULL, PRIMARY KEY (stat_uuid));
CREATE TABLE build_general.city (city_uuid uniqueidentifier NOT NULL, city_value nvarchar(max) NOT NULL, stat_uuid uniqueidentifier NOT NULL, PRIMARY KEY (city_uuid));
CREATE TABLE build_general.[user] (user_uuid uniqueidentifier NOT NULL, user_email nvarchar(max) NULL, user_value nvarchar(max) NULL, user_password nvarchar(max) NOT NULL, user_fullname nvarchar(max) NOT NULL, user_gender bit NOT NULL, user_landline nvarchar(max) NULL, user_cellphonenumber nvarchar(max) NULL, user_preferences nvarchar(max) NULL, user_role tinyint NOT NULL, user_enabled bit NOT NULL, user_maximumhoursperiod tinyint NULL, user_minimumhoursperiod tinyint NULL, city_uuid uniqueidentifier NOT NULL, file_uuid_avatar uniqueidentifier NULL, user_uuid_root uniqueidentifier NULL, sess_uuid_used uniqueidentifier NULL, sess_uuid_created uniqueidentifier NOT NULL, sess_uuid_deleted uniqueidentifier NULL, PRIMARY KEY (user_uuid));
CREATE TABLE build_general.[session] (sess_uuid uniqueidentifier NOT NULL, sess_starttime time(0) NOT NULL, sess_endtime time(0) NULL, sess_ipbatch01 nvarchar(max) NOT NULL, sess_ipbatch02 nvarchar(max) NOT NULL, sess_ipbatch03 nvarchar(max) NOT NULL, sess_ipbatch04 nvarchar(max) NOT NULL, user_uuid uniqueidentifier NOT NULL, date_uuid uniqueidentifier NOT NULL, PRIMARY KEY (sess_uuid));
CREATE TABLE build_general.[date] (date_uuid uniqueidentifier NOT NULL, date_value date NOT NULL, PRIMARY KEY (date_uuid));
CREATE TABLE build_general.appointment (appo_uuid uniqueidentifier NOT NULL, appo_time time(0) NOT NULL, appo_cancel bit DEFAULT 0 NOT NULL, date_uuid uniqueidentifier NOT NULL, brof_uuid uniqueidentifier NOT NULL, appo_uuid_root uniqueidentifier NULL, sess_uuid_used uniqueidentifier NULL, sess_uuid_created uniqueidentifier NOT NULL, sess_uuid_deleted uniqueidentifier NULL, PRIMARY KEY (appo_uuid));
CREATE TABLE build_general.class (clas_uuid uniqueidentifier NOT NULL, clas_folio nvarchar(10) NOT NULL, clas_time time(0) NOT NULL, user_uuid_teacher uniqueidentifier NOT NULL, clro_uuid uniqueidentifier NOT NULL, date_uuid uniqueidentifier NOT NULL, brof_uuid uniqueidentifier NOT NULL, clas_uuid_root uniqueidentifier NULL, sess_uuid_used uniqueidentifier NULL, sess_uuid_created uniqueidentifier NOT NULL, sess_uuid_deleted uniqueidentifier NULL, PRIMARY KEY (clas_uuid));
CREATE TABLE build_general.class_user (clas_uuid uniqueidentifier NOT NULL, user_uuid uniqueidentifier NOT NULL, PRIMARY KEY (clas_uuid, user_uuid));
CREATE TABLE build_general.classroom (clro_uuid uniqueidentifier NOT NULL, clro_value nvarchar(max) NOT NULL, PRIMARY KEY (clro_uuid));
CREATE TABLE build_general.appointment_user (appo_uuid uniqueidentifier NOT NULL, user_uuid uniqueidentifier NOT NULL, PRIMARY KEY (appo_uuid, user_uuid));
CREATE TABLE build_general.kardex (kard_uuid uniqueidentifier NOT NULL, kard_level tinyint NOT NULL, kard_chapter tinyint NOT NULL, kard_type tinyint NOT NULL, kard_description nvarchar(max) NULL, kard_mistake tinyint NULL, user_uuid uniqueidentifier NOT NULL, date_uuid uniqueidentifier NOT NULL, kard_uuid_root uniqueidentifier NULL, sess_uuid_used uniqueidentifier NULL, sess_uuid_created uniqueidentifier NOT NULL, sess_uuid_deleted uniqueidentifier NULL, PRIMARY KEY (kard_uuid));
CREATE TABLE build_general.club (club_uuid uniqueidentifier NOT NULL, club_folio nvarchar(10) NOT NULL, club_time time(0) NOT NULL, user_uuid_teacher uniqueidentifier NOT NULL, date_uuid uniqueidentifier NOT NULL, brof_uuid uniqueidentifier NOT NULL, club_uuid_root uniqueidentifier NULL, sess_uuid_used uniqueidentifier NULL, sess_uuid_created uniqueidentifier NOT NULL, sess_uuid_deleted uniqueidentifier NULL, PRIMARY KEY (club_uuid));
CREATE TABLE build_general.club_user (club_uuid uniqueidentifier NOT NULL, user_uuid uniqueidentifier NOT NULL, PRIMARY KEY (club_uuid, user_uuid));
CREATE TABLE build_general.[file] (file_uuid uniqueidentifier NOT NULL, [file_name] nvarchar(max) NOT NULL, file_extension tinyint NOT NULL, file_description nvarchar(max) NULL, file_value varbinary(max) NOT NULL, PRIMARY KEY (file_uuid));
CREATE TABLE build_general.branchoffice (brof_uuid uniqueidentifier NOT NULL, brof_value nvarchar(max) NOT NULL, PRIMARY KEY (brof_uuid));
CREATE TABLE build_general.branchoffice_user (brof_uuid uniqueidentifier NOT NULL, user_uuid uniqueidentifier NOT NULL, PRIMARY KEY (brof_uuid, user_uuid));

GO

--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'AGUASCALIENTES')
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'BAJA CALIFORNIA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'BAJA CALIFORNIA SUR');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'CAMPECHE');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'CHIAPAS');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'CHIHUAHUA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'COAHUILA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'COLIMA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'DISTRITO FEDERAL');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'DURANGO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'GUANAJUATO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'GUERRERO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'HIDALGO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'JALISCO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'MÉXICO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'MICHOACÁN');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'MORELOS');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'NAYARIT');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'NUEVO LEÓN');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'OAXACA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'PUEBLA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'QUERÉTARO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'QUINTANA ROO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'SAN LUIS POTOSÍ');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'SINALOA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'SONORA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'TABASCO');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'TAMAULIPAS');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'TLAXCALA');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'VERACRUZ');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'YUCATÁN');
--INSERT INTO build_general.[state](stat_uuid, stat_value) VALUES('', 'ZACATECAS');
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AGUASCALIENTES',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ASIENTOS',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CALVILLO',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COSÍO',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JESÚS MARÍA',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PABELLÓN DE ARTEAGA',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RINCÓN DE ROMOS',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FRANCISCO DE LOS ROMO',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPEZALÁ',  1);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ENSENADA',  2);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MEXICALI',  2);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PLAYAS DE ROSARITO',  2);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RODOLFO SÁNCHEZ T. MANEADERO',  2);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FELIPE',  2);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TECATE',  2);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIJUANA',  2);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CABO SAN LUCAS',  3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD CONSTITUCIÓN',  3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUERRERO NEGRO', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA MULEGÉ', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA PAZ', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LORETO', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUERTO ADOLFO LÓPEZ MATEOS', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN IGNACIO', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JOSÉ DEL CABO', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TODOS SANTOS', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA ALBERTO ANDRÉS ALVARADO ARÁMBURO', 3);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CALKINI', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CANDELARIA', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHAMPOTÓN', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD DEL CARMEN', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ESCÁRCEGA', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HECELCHAKÁN', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HOPELCHÉN', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('POMUCH', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SABANCUY', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FRANCISCO DE CAMPECHE', 4);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACALA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ARRIAGA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CACAHOATÁN', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHIAPA DE CORZO', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CINTALAPA DE FIGUEROA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COMITÁN DE DOMÍNGUEZ', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUIXTLA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JIQUIPILAS', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAS MARGARITAS', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAS ROSAS', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MAPASTEPEC', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MOTOZINTLA DE MENDOZA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OCOSINGO', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OCOZOCOAUTLA DE ESPINOSA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PALENQUE', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PICHUCALCO', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PIJIJIAPAN', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUERTO MADERO SAN BENITO', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('REFORMA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN CRISTÓBAL DE LAS CASAS', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAPACHULA DE CÓRDOVA Y ORDÓÑEZ', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TONALÁ', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TUXTLA GUTIÉRREZ', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VENUSTIANO CARRANZA', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLAFLORES', 5);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BACHÍNIVA', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHIHUAHUA', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COLONIA ANÁHUAC', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAUHTÉMOC', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('DELICIAS', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HIDALGO DEL PARRAL', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JOSÉ MARIANO JIMÉNEZ', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JUAN ALDAMA', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JUÁREZ', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MADERA', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MANUEL OJINAGA', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NUEVO CASAS GRANDES', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA ROSALÍA DE CAMARGO', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAUCILLO', 6);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ALLENDE', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ARTEAGA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CASTAÑOS', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD ACUÑA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD MELCHOR MUZQUIZ', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUATRO CIÉNEGAS DE CARRANZA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FRANCISCO I. MADERO CHÁVEZ', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FRONTERA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MATAMOROS', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MONCLOVA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MORELOS', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NADADORES', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NAVA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NUEVA ROSITA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PARRAS DE LA FUENTE', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PIEDRAS NEGRAS', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RAMOS ARIZPE', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SABINAS', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SALTILLO', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN BUENAVENTURA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TORREÓN', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VIESCA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZARAGOZA', 7);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD DE ARMERÍA', 8);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD DE VILLA DE ÁLVAREZ', 8);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COLIMA', 8);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MANZANILLO', 8);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TECOMAN', 8);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ÁLVARO OBREGÓN', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AZCAPOTZALCO', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BENITO JUÁREZ', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COYOACÁN', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAJIMALPA DE MORELOS', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAUHTÉMOC', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUSTAVO A. MADERO', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IZTACALCO', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IZTAPALAPA', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA MAGDALENA CONTRERAS', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MIGUEL HIDALGO', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MILPA ALTA', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLÁHUAC', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLALPAN', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VENUSTIANO CARRANZA', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('XOCHIMILCO', 9);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CANATLÁN', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD LERDO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL SALTO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FRANCISCO I. MADERO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GÓMEZ PALACIO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NOMBRE DE DIOS', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PEÑÓN BLANCO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN DEL RÍO DEL CENTAURO DEL NORTE', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA MARÍA DEL ORO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO PAPASQUIARO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VICENTE GUERRERO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VICTORIA DE DURANGO', 10);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ABASOLO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACÁMBARO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('APASEO EL ALTO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('APASEO EL GRANDE', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CELAYA', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD MANUEL DOBLADO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COMONFORT', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CORTAZAR', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUERÁMARO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('DOCTOR MORA', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EMPALME ESCOBEDO ESCOBEDO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUANAJUATO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUANÍMARO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IRAPUATO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JARAL DEL PROGRESO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JERÉCUARO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LEÓN DE LOS ALDAMA', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MARFIL', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MOROLEÓN', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PÉNJAMO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PURÍSIMA DE BUSTOS', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RINCÓN DE TAMAYO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ROMITA', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SALAMANCA', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SALVATIERRA', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN DIEGO DE LA UNIÓN', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FRANCISCO DEL RINCÓN', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JOSÉ ITURBIDE', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN LUIS DE LA PAZ', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN MIGUEL DE ALLENDE', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA CRUZ JUVENTINO ROSAS', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO MARAVATÍO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SILAO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TARANDACUAO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('URIANGATO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VALLE DE SANTIAGO', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLAGRÁN', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('YURIRIA', 11);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACAPULCO DE JUÁREZ', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ARCELIA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ATOYAC DE ÁLVAREZ', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AYUTLA DE LOS LIBRES', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AZOYÚ', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BUENAVISTA DE CUELLAR', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHILAPA DE ÁLVAREZ', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHILPANCINGO DE LOS BRAVO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD ALTAMIRANO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD APAXTLA DE CASTREJÓN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COPALA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COYUCA DE BENÍTEZ', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COYUCA DE CATALÁN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CRUZ GRANDE', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAJINICUILAPA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUTZAMALA DE PINZÓN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUAMUXTITLAN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUITZUCO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IGUALA DE LA INDEPENDENCIA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA UNIÓN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MARQUELIA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OCOTITO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OLINALÁ', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PETATLÁN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JERÓNIMO DE JUÁREZ', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN LUIS ACATLÁN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN LUIS DE LA LOMA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN LUIS SAN PEDRO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN MARCOS', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAXCO DE ALARCÓN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TÉCPAN DE GALEANA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TELOLOAPAN', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPECOACUILCO DE TRUJANO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIERRA COLORADA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIXTLA DE GUERRERO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLALIXTAQUILLA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAPA DE COMONFORT', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAPEHUALA', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZIHUATANEJO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZUMPANGO DEL RÍO', 12);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACTOPAN', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('APAN', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD DE FRAY BERNARDINO DE SAHAGÚN', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CRUZ AZUL', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUEJUTLA DE REYES', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IXMIQUILPAN', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PACHUCA DE SOTO', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO TULANTEPEC', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPEAPULCO', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPEJI DEL RIO', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIZAYUCA', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAXCOAPAN', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TULA DE ALLENDE', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TULANCINGO', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZIMAPAN', 13);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACATLÁN DE JUÁREZ', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AHUALULCO DE MERCADO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AJIJIC', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AMECA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ARANDAS', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ATOTONILCO EL ALTO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AUTLÁN DE NAVARRO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHAPALA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIHUATLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD GUZMÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COCULA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COLOTLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL GRULLO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL QUINCE SAN JOSÉ EL QUINCE', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ETZATLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUADALAJARA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUEJUQUILLA EL ALTO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JALOSTOTITLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JAMAY', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JOCOTEPEC', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA BARCA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA RESOLANA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAGOS DE MORENO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAS PINTITAS', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MAGDALENA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OCOTLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PONCITLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUERTO VALLARTA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN DIEGO DE ALEJANDRÍA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN IGNACIO CERRO GORDO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JOSÉ EL VERDE EL VERDE', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN DE LOS LAGOS', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JULIÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN MIGUEL EL ALTO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAYULA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TALA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TALPA DE ALLENDE', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAMAZULA DE GORDIANO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TECALITLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEOCALTICHE', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPATITLÁN DE MORELOS', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEQUILA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAJOMULCO DE ZÚÑIGA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAQUEPAQUE', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TONALÁ', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TOTOTLÁN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TUXPAN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('UNIÓN DE SAN ANTONIO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VALLE DE GUADALUPE', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA CORONA', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA HIDALGO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('YAHUALICA DE GONZÁLEZ GALLO', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZACOALCO DE TORRES', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZAPOPAN', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZAPOTILTIC', 14);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ALMOLOYA DE JUÁREZ', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AMATEPEC', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CAPULHUAC', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHALCO DE DÍAZ COVARRUBIAS', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHICONCUAC', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHIMALHUACÁN', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD ADOLFO LÓPEZ MATEOS', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD NEZAHUALCOYOTL', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COACALCO DE BERRIOZABAL', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAUTITLÁN', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAUTITLÁN IZCALLI', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ECATEPEC DE MORELOS', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUIXQUILUCAN DE DEGOLLADO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IXTAPALUCA', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JUCHITEPEC DE MARIANO RIVA PALACIO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LOS REYES ACAQUILPAN LA PAZ', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MELCHOR OCAMPO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('METEPEC', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NAUCALPAN DE JUÁREZ', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OCOYOACAC', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN MATEO ATENCO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN VICENTE CHICOLOAPAN DE JUÁREZ', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA MARIA TULTEPEC', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TECAMAC DE FELIPE VILLANUEVA', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEJUPILCO DE HIDALGO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPOTZOTLÁN', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEQUIXQUIAC', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEXCOCO DE MORA', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLALNEPANTLA DE BAZ', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TOLUCA DE LERDO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TULTITLÁN DE MARIANO ESCOBEDO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VALLE DE CHALCO SOLIDARIDAD', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA NICOLÁS ROMERO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('XONACATLÁN', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZUMPANGO', 15);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('APATZINGÁN DE LA CONSTITUCIÓN', 16);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD HIDALGO', 16);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD LÁZARO CÁRDENAS', 16);
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COTIJA DE LA PAZ',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUITZEO DEL PORVENIR',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA ZITÁCUARO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUETAMO DE NÚÑEZ',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JACONA DE PLANCARTE',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JIQUILPAN DE JUÁREZ',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA PIEDAD DE CABADAS',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAS GUACAMAYAS',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LOS REYES DE SALGADO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MARAVATÍO DE OCAMPO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MORELIA',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NUEVA ITALIA DE RUIZ',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PARACHO DE VERDUZCO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PÁTZCUARO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PURUÁNDIRO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAHUAYO DE MORELOS',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TACÁMBARO DE CODALLOS',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TANGANCÍCUARO DE ARISTA',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TUXPAN',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('URUAPAN',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('YURÉCUARO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZACAPU',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZAMORA DE HIDALGO',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZINAPÉCUARO DE FIGUEROA',16); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAUTLA CUAUTLA DE MORELOS',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUERNAVACA',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GALEANA',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JOJUTLA',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUENTE DE IXTLA',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA ROSA TREINTA',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAQUILTENANGO',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZACATEPEC DE HIDALGO',17); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACAPONETA',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AHUACATLÁN',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BUCERÍAS',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COMPOSTELA',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FRANCISCO I. MADERO (PUGA)',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IXTLÁN DEL RÍO',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JALA',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA PEÑITA DE JALTEMBA',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAS VARAS',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RUIZ',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN BLAS',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO LAGUNILLAS',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO IXCUINTLA',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TECUALA',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPIC',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TUXPAN',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA HIDALGO EL NUEVO',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('XALISCO',18); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ANÁHUAC',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CADEREYTA JIMÉNEZ',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIÉNEGA DE FLORES',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD APODACA',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD BENITO JUÁREZ',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD GENERAL ESCOBEDO',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD SABINAS HIDALGO',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD SANTA CATARINA',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('DOCTOR ARROYO',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL CERCADO',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GARCÍA',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUADALUPE',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUALAHUISES',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LINARES',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MONTEMORELOS',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MONTERREY',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN NICOLÁS DE LOS GARZA',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO GARZA GARCÍA',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO',19); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ASUNCIÓN NOCHIXTLÁN',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BAHIAS DE HUATULCO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHAHUITES',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD IXTEPEC',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COSOLAPA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUILÁPAM DE GUERRERO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL CAMARÓN',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL ROSARIO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA CIUDAD DE EJUTLA DE CRESPO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA CIUDAD DE HUAJUAPAN DE LEÓN',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA CIUDAD DE TLAXIACO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JUCHITÁN (JUCHITÁN DE ZARAGOZA)',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAGUNAS',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LOMA BONITA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MARISCALA DE JUÁREZ',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MATÍAS ROMERO AVENDAÑO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MIAHUATLÁN DE PORFIRIO DÍAZ',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NATIVIDAD',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OAXACA DE JUÁREZ',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OCOTLÁN DE MORELOS',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUERTO ESCONDIDO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUTLA VILLA DE GUERRERO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RÍO GRANDE O PIEDRA PARADA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SALINA CRUZ',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN ANTONIO DE LA CAL',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN BLAS ATEMPA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FELIPE JALAPA DE DÍAZ',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FRANCISCO IXHUATÁN',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FRANCISCO TELIXTLAHUACA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN BAUTISTA CUICATLÁN',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN BAUTISTA LO DE SOTO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN BAUTISTA TUXTEPEC',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN BAUTISTA VALLE NACIONAL',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN CACAHUATEPEC',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN MIGUEL EL GRANDE',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PABLO HUITZO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PABLO VILLA DE MITLA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO MIXTEPEC DTO. 22',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO POCHUTLA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO TAPANATEPEC',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO TOTOLAPA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN SEBASTIÁN TECOMAXTLAHUACA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA CRUZ ITUNDUJIA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA LUCIA DEL CAMINO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA MARÍA HUATULCO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO JAMILTEPEC',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO JUXTLAHUACA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO PINOTEPA NACIONAL',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO SUCHILQUITONGO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTO DOMINGO TEHUANTEPEC',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEOTITLÁN DE FLORES MAGÓN',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLACOLULA DE MATAMOROS',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('UNIÓN HIDALGO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VICENTE CAMALOTE',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA DE TAMAZULÁPAM DEL PROGRESO',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA DE ZAACHILA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA SOLA DE VEGA',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZIMATLÁN DE ÁLVAREZ',20); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACATLÁN DE OSORIO',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AMOZOC',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ATLIXCO',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD SERDÁN',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUAUTLANCINGO',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUAUCHINANGO',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IZÚCAR DE MATAMOROS',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUEBLA HEROICA PUEBLA',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN ANDRÉS CHOLULA',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN MARTÍN TEXMELUCAN DE LABASTIDA',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN PEDRO CHOLULA',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TECAMACHALCO',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEHUACAN',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEPEACA',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEZIUTLAN',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('XICOTEPEC',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZACATLÁN',21); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL PUEBLITO',22); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('QUERÉTARO',22); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN JUAN DEL RIO',22); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BACALAR',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CANCÚN',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHETUMAL',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COZUMEL',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FELIPE CARRILLO PUERTO',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ISLA MUJERES',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('KANTUNILKÍN',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PLAYA DEL CARMEN',23); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CÁRDENAS',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CEDRAL',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CERRITOS',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHARCAS',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD DEL MAÍZ',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD VALLES',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ÉBANO',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL NARANJO',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FRACCIÓN EL REFUGIO',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MATEHUALA',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RIOVERDE',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SALINAS DE HIDALGO',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN LUIS POTOSÍ',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTA MARÍA DEL RÍO',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SOLEDAD DE GRACIANO SÁNCHEZ',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAMASOPO',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAMAZUNCHALE',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAMUIN',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIERRA NUEVA',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA DE REYES',24); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AGUARUTO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AHOME',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ANGOSTURA',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHOIX',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COSALÁ',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CULIACÁN ROSALES',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL ROSARIO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ESCUINAPA DE HIDALGO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ESTACIÓN NARANJO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUAMÚCHIL',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUASAVE',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HIGUERA DE ZARAGOZA',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LA CRUZ',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LIC. BENITO JUÁREZ CAMPO GOBIERNO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LOS MOCHIS',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MAZATLÁN',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MOCORITO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NAVOLATO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('QUILA',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN BLAS',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN IGNACIO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SINALOA DE LEYVA',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TOPOLOBAMPO',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA UNIÓN',25); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AGUA PRIETA',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD OBREGÓN',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EMPALME',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HERMOSILLO',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA CABORCA',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA CIUDAD DE CANANEA',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA GUAYMAS',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA NOGALES',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUATABAMPO',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MAGDALENA DE KINO',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NAVOJOA',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PUERTO PEÑASCO',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN LUIS RÍO COLORADO',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SONOITA',26); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CÁRDENAS',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COMALCALCO',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUNDUACÁN',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EMILIANO ZAPATA',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FRONTERA',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUIMANGUILLO',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JALPA DE MÉNDEZ',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MACUSPANA',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PARAÍSO',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEAPA',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TENOSIQUE DE PINO SUÁREZ',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLAHERMOSA',27); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ALTAMIRA',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD CAMARGO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD GUSTAVO DÍAZ ORDAZ',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD MADERO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD MANTE',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD MIGUEL ALEMÁN',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD RÍO BRAVO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD TULA',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD VICTORIA',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ESTACIÓN MANUEL ÚRSULO GALVÁN',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GONZÁLEZ',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HEROICA MATAMOROS',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JAUMAVE',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NUEVA CIUDAD GUERRERO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NUEVO LAREDO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('REYNOSA',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN FERNANDO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SOTO LA MARINA',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAMPICO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VALLE HERMOSO',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('XICOTÉNCATL',28); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('APIZACO',29); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CALPULALPAN',29); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CHIAUTEMPAN',29); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUAMANTLA',29); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAXCALA TLAXCALA DE XICOTENCATL',29); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA VICENTE GUERRERO',29); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ACAYUCAN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('AGUA DULCE',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ALTOTONGA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ALVARADO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ÁNGEL R. CABADA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ATOYAC',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BANDERILLA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('BOCA DEL RÍO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CARLOS A. CARRILLO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CATEMACO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CAZONES DE HERRERA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CERRO AZUL',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COATEPEC',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COATZACOALCOS',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COATZINTLA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CÓRDOBA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COSAMALOAPAN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('COSOLEACAQUE',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUICHAPA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CUITLÁHUAC',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('EL HIGO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FORTÍN DE LAS FLORES',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GENERAL MIGUEL ALEMÁN POTRERO NUEVO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUTIÉRREZ ZAMORA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUATUSCO DE CHICUELLAR',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUAYACOCOTLA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('HUILOAPAN DE CUAUHTÉMOC',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ISLA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('IXTACZOQUITLÁN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JÁLTIPAN DE MORELOS',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JOSÉ CARDEL',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JUAN DÍAZ COVARRUBIAS',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JUAN RODRÍGUEZ CLARA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LAS CHOAPAS',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LERDO DE TEJADA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MINATITLÁN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NARANJOS',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NOGALES',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ORIZABA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PÁNUCO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PAPANTLA DE OLARTE',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PARAJE NUEVO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PASO DE OVEJAS',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PASO DEL MACHO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PLATÓN SÁNCHEZ',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('PLAYA VICENTE',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('POZA RICA DE HIDALGO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RÍO BLANCO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN ANDRÉS TUXTLA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SAN RAFAEL',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SANTIAGO TUXTLA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SIHUAPAN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SOLEDAD DE DOBLADO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TAMPICO ALTO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TANTOYUCA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEMPOAL DE SÁNCHEZ',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TEZONAPA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIERRA BLANCA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIHUATLÁN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLACOJALPAN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TLAPACOYAN',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TRES VALLES',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TÚXPAM DE RODRÍGUEZ CANO',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VERACRUZ',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('XALAPA-ENRÍQUEZ',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('YECUATLA',30); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MÉRIDA',31); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MOTUL DE CARRILLO PUERTO',31); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TICUL',31); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('TIZIMÍN',31); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VALLADOLID',31); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('CIUDAD CUAUHTÉMOC',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('FRESNILLO',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('GUADALUPE',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JALPA',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JEREZ DE GARCÍA SALINAS',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('JUAN ALDAMA',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LORETO',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('LUIS MOYA',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('MOYAHUA DE ESTRADA',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('NOCHISTLÁN DE MEJÍA',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('OJOCALIENTE',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('RÍO GRANDE',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('SOMBRERETE',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VALPARAÍSO',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VÍCTOR ROSALES',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA DE COS',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLA HIDALGO',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('VILLANUEVA',32); 
--INSERT INTO build_general.city(city_value, stat_uuid) VALUES('ZACATECAS',32);
INSERT INTO build_general.[date](date_uuid, date_value) VALUES('', GETDATE());
INSERT INTO build_general.[session](
	sess_starttime, sess_endtime, sess_ipbatch01, sess_ipbatch02, sess_ipbatch03, sess_ipbatch04, user_uuid, date_uuid) 
	VALUES('00:00:00:001', '00:00:00:002', 001, 001, 001, 001, '', '');
INSERT INTO build_general.[user](
	user_email, user_value, user_password, user_fullname, user_gender, user_landline, user_cellphonenumber, user_preferences, user_role, user_enabled, 
	user_maximumhoursperiod, user_minimumhoursperiod, city_uuid, file_uuid_avatar, user_uuid_root, sess_uuid_used, sess_uuid_created, sess_uuid_deleted) 
	VALUES(NULL, 'cristyn98', '89nirc', 'Cristina', 0, NULL, NULL, NULL, 3, 1, NULL, NULL, '', NULL, NULL, NULL, '', NULL);

GO

ALTER TABLE build_general.city ADD CONSTRAINT FKcity907242 FOREIGN KEY (stat_uuid) REFERENCES build_general.[state] (stat_uuid);
ALTER TABLE build_general.[user] ADD CONSTRAINT FKuser290109 FOREIGN KEY (city_uuid) REFERENCES build_general.city (city_uuid);
ALTER TABLE build_general.[user] ADD CONSTRAINT FKuser793144 FOREIGN KEY (sess_uuid_created) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.[session] ADD CONSTRAINT FKsession244700 FOREIGN KEY (user_uuid) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.[user] ADD CONSTRAINT FKuser884093 FOREIGN KEY (sess_uuid_deleted) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.[session] ADD CONSTRAINT FKsession430830 FOREIGN KEY (date_uuid) REFERENCES build_general.[date] (date_uuid);
ALTER TABLE build_general.[user] ADD CONSTRAINT FKuser223585 FOREIGN KEY (user_uuid_root) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.class_user ADD CONSTRAINT FKclass_user862929 FOREIGN KEY (clas_uuid) REFERENCES build_general.class (clas_uuid);
ALTER TABLE build_general.class_user ADD CONSTRAINT FKclass_user487651 FOREIGN KEY (user_uuid) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass815953 FOREIGN KEY (date_uuid) REFERENCES build_general.[date] (date_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass649456 FOREIGN KEY (sess_uuid_created) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.appointment ADD CONSTRAINT FKappointmen555724 FOREIGN KEY (date_uuid) REFERENCES build_general.[date] (date_uuid);
ALTER TABLE build_general.appointment_user ADD CONSTRAINT FKappointmen819128 FOREIGN KEY (appo_uuid) REFERENCES build_general.appointment (appo_uuid);
ALTER TABLE build_general.appointment_user ADD CONSTRAINT FKappointmen799931 FOREIGN KEY (user_uuid) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass95460 FOREIGN KEY (clro_uuid) REFERENCES build_general.classroom (clro_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass603448 FOREIGN KEY (user_uuid_teacher) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.kardex ADD CONSTRAINT FKkardex131168 FOREIGN KEY (date_uuid) REFERENCES build_general.[date] (date_uuid);
ALTER TABLE build_general.kardex ADD CONSTRAINT FKkardex835107 FOREIGN KEY (user_uuid) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.club ADD CONSTRAINT FKclub502127 FOREIGN KEY (date_uuid) REFERENCES build_general.[date] (date_uuid);
ALTER TABLE build_general.club ADD CONSTRAINT FKclub289622 FOREIGN KEY (user_uuid_teacher) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.club_user ADD CONSTRAINT FKclub_user46942 FOREIGN KEY (club_uuid) REFERENCES build_general.club (club_uuid);
ALTER TABLE build_general.club_user ADD CONSTRAINT FKclub_user65792 FOREIGN KEY (user_uuid) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass740405 FOREIGN KEY (sess_uuid_deleted) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.[user] ADD CONSTRAINT FKuser85277 FOREIGN KEY (sess_uuid_used) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass941588 FOREIGN KEY (sess_uuid_used) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.[user] ADD CONSTRAINT FKuser581178 FOREIGN KEY (file_uuid_avatar) REFERENCES build_general.[file] (file_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass126293 FOREIGN KEY (brof_uuid) REFERENCES build_general.branchoffice (brof_uuid);
ALTER TABLE build_general.club ADD CONSTRAINT FKclub159124 FOREIGN KEY (brof_uuid) REFERENCES build_general.branchoffice (brof_uuid);
ALTER TABLE build_general.class ADD CONSTRAINT FKclass423549 FOREIGN KEY (clas_uuid_root) REFERENCES build_general.class (clas_uuid);
ALTER TABLE build_general.appointment ADD CONSTRAINT FKappointmen105527 FOREIGN KEY (brof_uuid) REFERENCES build_general.branchoffice (brof_uuid);
ALTER TABLE build_general.appointment ADD CONSTRAINT FKappointmen582363 FOREIGN KEY (sess_uuid_created) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.appointment ADD CONSTRAINT FKappointmen491414 FOREIGN KEY (sess_uuid_deleted) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.appointment ADD CONSTRAINT FKappointmen290231 FOREIGN KEY (sess_uuid_used) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.appointment ADD CONSTRAINT FKappointmen84063 FOREIGN KEY (appo_uuid_root) REFERENCES build_general.appointment (appo_uuid);
ALTER TABLE build_general.kardex ADD CONSTRAINT FKkardex924093 FOREIGN KEY (kard_uuid_root) REFERENCES build_general.kardex (kard_uuid);
ALTER TABLE build_general.kardex ADD CONSTRAINT FKkardex6920 FOREIGN KEY (sess_uuid_created) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.kardex ADD CONSTRAINT FKkardex915970 FOREIGN KEY (sess_uuid_deleted) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.kardex ADD CONSTRAINT FKkardex256803 FOREIGN KEY (sess_uuid_used) REFERENCES build_general.[session] (sess_uuid);
ALTER TABLE build_general.branchoffice_user ADD CONSTRAINT FKbranchoff721371 FOREIGN KEY (brof_uuid) REFERENCES build_general.branchoffice (brof_uuid);
ALTER TABLE build_general.branchoffice_user ADD CONSTRAINT FKbranchoff86563 FOREIGN KEY (user_uuid) REFERENCES build_general.[user] (user_uuid);
ALTER TABLE build_general.club ADD CONSTRAINT FKclub351960 FOREIGN KEY (club_uuid_root) REFERENCES build_general.club (club_uuid);
ALTER TABLE build_general.club ADD CONSTRAINT FKclub627762 FOREIGN KEY (sess_uuid_used) REFERENCES build_general.session (sess_uuid);
ALTER TABLE build_general.club ADD CONSTRAINT FKclub335630 FOREIGN KEY (sess_uuid_created) REFERENCES build_general.session (sess_uuid);
ALTER TABLE build_general.club ADD CONSTRAINT FKclub426579 FOREIGN KEY (sess_uuid_deleted) REFERENCES build_general.session (sess_uuid);

GO

CREATE UNIQUE INDEX state_stat_value ON build_general.[state] (stat_value);
CREATE INDEX city_city_value ON build_general.city (city_value);
CREATE INDEX user_user_email ON build_general.[user] (user_email);
CREATE INDEX user_user_value ON build_general.[user] (user_value);
CREATE INDEX user_user_cellphonenumber ON build_general.[user] (user_cellphonenumber);
CREATE UNIQUE INDEX date_date_value ON build_general.[date] (date_value);
CREATE INDEX class_clas_folio ON build_general.class (clas_folio);
CREATE INDEX classroom_clro_value ON build_general.classroom (clro_value);
CREATE INDEX club_club_folio ON build_general.club (club_folio);
CREATE INDEX branchoffice_brof_value ON build_general.branchoffice (brof_value);
